
import OpenAI from 'openai';
import * as dotenv from 'dotenv';

// --- Step 1: Initialize Libraries ---
// Load environment variables from your .env file
dotenv.config();

// Initialize the OpenAI client with the API key from the .env file
const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});


/**
 * Generates a unique, human-like comment using the OpenAI API based on the post's caption.
 * This function is now async as it makes a network request.
 * @param {string} caption The caption of the Instagram post.
 * @returns {Promise<string>} A relevant comment generated by the AI.
 */
async function generateComment(caption: string): Promise<string> {
    // If the caption is empty or too short, return a generic comment immediately.
    if (!caption || caption.trim().length < 5) {
        return 'Looks great! ✨';
    }

    // This is the "prompt" you send to the AI.
    // It gives the AI context and instructions for the kind of comment you want.
    const prompt = `
        You are an enthusiastic and friendly Instagram user.
        Your task is to write a short, positive, and engaging comment for an Instagram post.

        Rules:
        - The comment must be 1-2 sentences long.
        - Use 1 or 2 relevant emojis.
        - Sound natural and not like a bot.
        - Do not use hashtags.
        - Base the comment on the post's caption below.

        Post Caption: "${caption}"
    `;

    try {
        console.log('Contacting OpenAI to generate a comment...');
        const response = await openai.chat.completions.create({
            model: "gpt-3.5-turbo", // A fast and cost-effective model for this task
            messages: [{
                role: "user",
                content: prompt,
            }],
            max_tokens: 60,       // Restricts the length of the response
            temperature: 0.8,     // Makes the output creative but not too random
        });

        // Safely extract the comment from the AI's response
        const comment = response.choices[0]?.message?.content?.trim();
        
        // If a valid comment was generated, return it. Otherwise, use a fallback.
        return comment || 'Love this post! 🙌';

    } catch (error) {
        console.error("Error calling OpenAI API:", error);
        // If the API call fails, return a safe, generic comment so the script doesn't stop.
        return 'Awesome post! 👍';
    }
}

describe('Instagram Loop Commenting with OpenAI', () => {

    // This test assumes you are already on a post grid (e.g., for a location or hashtag).
    it('should loop through and comment on 5 specific posts using AI-generated comments', async () => {

        console.log('--- Starting AI Comment Loop ---');
        await driver.pause(3000);

        // Find all available posts in the grid
        const postSelectors = [
            '//android.widget.FrameLayout[@content-desc and contains(@content-desc, "row 1, column 1")]',
            '//android.widget.FrameLayout[@content-desc and contains(@content-desc, "row 1, column 2")]', 
            '//android.widget.FrameLayout[@content-desc and contains(@content-desc, "row 1, column 3")]',
            '//android.widget.FrameLayout[@content-desc and contains(@content-desc, "Row 2, Column 1")]',
            '//android.widget.FrameLayout[@content-desc and contains(@content-desc, "row 2, column 2")]'
        ];

        let postsCommented = 0;

        for (let i = 0; i < postSelectors.length; i++) {
            console.log(`\n--- Attempting to process post ${i + 1} ---`);

            const postElement = await $(postSelectors[i]);

            try {
                await postElement.waitForDisplayed({ timeout: 10000 });
                await postElement.click();
                console.log(`Clicked on post ${i + 1}.`);
            } catch (error) {
                console.error(`Could not find or click post ${i + 1}. Skipping.`);
                continue; // Skip to the next post if this one isn't found
            }
            
            await driver.pause(2000);

            // --- Commenting Logic using OpenAI ---
            // Scroll down a bit to ensure comment button is visible
            await driver.performActions([{
                type: 'pointer',
                id: 'finger1',
                actions: [
                    { type: 'pointerMove', duration: 0, x: 500, y: 800 },
                    { type: 'pointerDown', button: 0 },
                    { type: 'pointerMove', duration: 500, x: 500, y: 600 },
                    { type: 'pointerUp', button: 0 }
                ]
            }]);
            await driver.pause(1000);
            
            const commentButton = await $('//android.widget.Button[@content-desc="Comment"]');
            await commentButton.waitForDisplayed({ timeout: 10000 });
            await commentButton.click();
            await driver.pause(3000);

            // Get caption text from the post (look for the text next to username)
            let captionText = 'Great post!';
            try {
                const captionElement = await $('//com.instagram.ui.widget.textview.IgTextLayoutView');
                await captionElement.waitForDisplayed({ timeout: 5000 });
                captionText = await captionElement.getText();
                // Remove username from caption if present
                captionText = captionText.replace(/^\w+\s+/, '');
            } catch (error) {
                console.log('Could not find caption, using fallback text');
            }
            
            // **IMPORTANT:** We now use 'await' because generateComment makes an API call.
            const commentToPost = await generateComment(captionText);
            
            console.log(`Generated AI Comment: "${commentToPost}"`);

            const commentInput = await $('//android.widget.AutoCompleteTextView[@resource-id="com.instagram.android:id/layout_comment_thread_edittext"]');
            await commentInput.waitForDisplayed({ timeout: 10000 });
            await commentInput.setValue(commentToPost);
            await driver.pause(2000);

            // Look for Post button (it appears after typing)
            try {
                const postCommentButton = await $('//android.widget.ImageView[@resource-id="com.instagram.android:id/layout_comment_thread_post_button_icon"]');
                await postCommentButton.waitForDisplayed({ timeout: 5000 });
                await postCommentButton.click();
            } catch (error) {
                console.log('Post button not found, pressing Enter instead');
                await driver.pressKeyCode(66); // Enter key
            }
            postsCommented++;
            console.log(`Posted comment #${postsCommented}.`);
            await driver.pause(3000);

            // --- Navigate back to the grid to continue the loop ---
            console.log('Navigating back to the post grid...');
            
            // Multiple back presses with verification
            for (let backStep = 1; backStep <= 4; backStep++) {
                console.log(`Back step ${backStep}...`);
                await driver.back();
                await driver.pause(1500);
                
                // After 3 back presses, check if we're at the grid
                if (backStep >= 3) {
                    try {
                        const gridCheck = await $('//android.widget.FrameLayout[@content-desc and contains(@content-desc, "row")]');
                        await gridCheck.waitForDisplayed({ timeout: 2000 });
                        console.log('Successfully returned to grid');
                        break;
                    } catch (error) {
                        console.log('Not at grid yet, continuing...');
                        if (backStep === 4) {
                            console.log('Max back attempts reached');
                        }
                    }
                }
            }
        }

        console.log(`\n✅ SUCCESS: Finished the loop. Commented on ${postsCommented} posts using OpenAI.`);
    });
});